image: node:14

stages:
  - install_dependencies
  - lint
  - test
  - build

cache:
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - node_modules/
    - dist/

install_dependencies:
  stage: install_dependencies
  script:
    - npm install
  tags:
    - node

lint:
  stage: lint
  script:
    - npm run lint:ci
  tags:
    - node

test:
  stage: test
  script:
    - npm run test:ci
  tags:
    - node

build:
  stage: build
  script:
    - npm run build
  tags:
    - node
